### PR TITLE
fix: tag colors in events

### PR DESCRIPTION
**Pull request by farhan711**
addressing issue -  https://github.com/HelpfulHuman/ShopifyExperiencesApp/issues/6390

Screenshot 2023-08-15 at 5 21 22 PM

cc: @markgustav

### CODE REVIEW

**Review by NickGlenn — APPROVED** [review]

**Comment by markgustav** [comment]
@NickGlenn Does this mean this was merged into production? 
If so, I'm still seeing unexpected behavior in production. 

- If two tags are assigned to a SKU, it won't display on calendar unless the second added tag is used, not when 2 or more existing tags are used in the filter
- If at least one filter tag is an actual Shopify tag assigned to the product but there are typed in fake tags in the filter, the product shows up
- Expected: Regardless of the number of actual tags, the product should show in the calendar as long as one tag requirement is satisfied

@farhan711 is this behavior happening because we're assigned colors based on actual tags and there can only be one tag at a time because each tag gets a color and our script wouldn't know what color to assign if there's more than one actual tag assigned to a SKU?

**Comment by ckeyes88** [comment]
@markgustav, @NickGlenn, and @farhan711 in order to release to production you have to tag a branch (usually master) for release. This is the case across all of our repositories.

**Comment by NickGlenn** [comment]
@ckeyes88 This one's all you buddy, I'm not familiar with the background of this effort.

**Comment by markgustav** [comment]
@ckeyes88 please lmk when this is done, done.

**Pull request merged**
